import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.swifttranslator.com/');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('yanuda mithura');
  await page.getByText('🔁 Translate🗑️ Clear').click();
  await page.locator('div').filter({ hasText: 'Singlishyanuda mithuraSinhala' }).nth(4).click();
  await page.getByText('මිතුරු වෙනවා').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Api denata yamu.');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Mata salli naha namuth mama sathutin.');
  await page.locator('div').filter({ hasText: 'SinglishMata salli naha' }).nth(4).click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Oya paadam keruwoth pass weyi.');
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Oba kawada enawada?');
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Wahaama meka denna.');
  await page.locator('.flex.items-center.gap-2.mt-2').first().click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.locator('div').filter({ hasText: /^Singlish$/ }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Ma langa pothak thibenawa.');
  await page.getByLabel('Clear').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Ma langa pothak naha.');
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Mata pan ekak denna.');
  await page.locator('div').filter({ hasText: 'SinglishMata pan ekak denna' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByLabel('Clear').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Theruwan saranai.');
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.locator('div').filter({ hasText: /^Singlish$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Singlish$/ }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Mokada ban karanne?');
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Bus eka awa.');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Budu ammo.');
  await page.locator('div').filter({ hasText: 'SinglishBudu ammo.Sinhala🔁' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Gedara yanna.');
  await page.locator('.w-full.h-80.p-3.rounded-lg.ring-1.ring-slate-300.whitespace-pre-wrap').click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click({
    modifiers: ['ControlOrMeta']
  });
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Gedarayanna.');
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Wara wara.');
  await page.locator('.w-full.h-80.p-3.rounded-lg.ring-1.ring-slate-300.whitespace-pre-wrap').click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Mama yanawa.');
  await page.locator('.w-full.h-80.p-3.rounded-lg.ring-1.ring-slate-300.whitespace-pre-wrap').click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).dblclick();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Mama yannam.');
  await page.locator('.w-full.h-80.p-3.rounded-lg.ring-1.ring-slate-300.whitespace-pre-wrap').click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click({
    modifiers: ['ControlOrMeta']
  });
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Mata \'Laptop\' eka oni.');
  await page.locator('.w-full.h-80.p-3.rounded-lg.ring-1.ring-slate-300.whitespace-pre-wrap').click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click({
    modifiers: ['ControlOrMeta']
  });
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Mage \'ID\' eka.');
  await page.locator('.w-full.h-80.p-3.rounded-lg.ring-1.ring-slate-300.whitespace-pre-wrap').click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Rs. 500 k denna.');
  await page.locator('.w-full.h-80.p-3.rounded-lg.ring-1.ring-slate-300.whitespace-pre-wrap').click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Maa visin me liyana lada lipiya sathyayak bava ma saththya karanawa. Mehi kisidu boruwak natha. Oba visin meya kiyawiya yuthuyi.');
  await page.locator('.w-full.h-80.p-3.rounded-lg.ring-1.ring-slate-300.whitespace-pre-wrap').click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('MMMYANNA');
  await page.locator('.w-full.h-80.p-3.rounded-lg.ring-1.ring-slate-300.whitespace-pre-wrap').click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('<script>');
  await page.locator('div').filter({ hasText: /^<script>$/ }).click();
  await page.getByRole('button', { name: 'Clear' }).first().click();
  await page.goto('about:blank');
});